### ISSUE TITLE
Could you please provide instructions about how to install this?

### ISSUE THREAD

**Issue by kavita-chitnis** [uber/multidimensional_urlencode#6]
I am very new to Python. I need to use the nested params for urllib encode. Could you please provide instructions for how to install your library?

**Comment by dawsonbotsford** [comment]
Because this is setup through pip (`pip search multidimensional_urlencode`) -> "`multidimensional_urlencode     - Urlencode a multidimensional dict`", you can install this with 

```python
pip install multidimensional_urlencode
```

After installed via pip, you can follow the "Quick Start" example on the readme. 

Closing this. Reopen if this doesn't answer your question. Thanks @kavita-chitnis!
